modLoader="javafml"
loaderVersion="[44,)"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"
logoFile="${mod_id}_icon.png"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.assortedcore]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.assortedcore]]
modId="minecraft"
mandatory=true
versionRange="${forge_mc_version_range}"
ordering="NONE"
side="BOTH"
